# Generated by Django 3.2.9 on 2021-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200)),
                ('body', models.CharField(default='body', max_length=1200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
