# Generated by Django 3.2.9 on 2021-12-02 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_note_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 8, 17, 26, 813810, tzinfo=utc)),
        ),
    ]
