# Generated by Django 3.2.9 on 2021-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='link',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
